# k8s/job-ml-ds2.yaml
apiVersion: batch/v1
kind: Job
metadata:
  # 1. Mudamos o nome para '005'
  name: playlist-ml-ds2-0020
  namespace: lucascosta
spec:
  backoffLimit: 1
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: ml-train
          # Usando a imagem v0.1 (que agora tem o código original sem amostragem)
          image: docker.io/lukasalbukk/playlist-ml:0.2
          imagePullPolicy: Always
          env:
            - name: DATASET_URL
              value: "https://raw.githubusercontent.com/LukasAlbkk/devops/main/datasets/2023_spotify_ds2.csv"
            - name: PLAYLIST_COL
              value: "pid"
            - name: SONG_COL
              value: "track_name"
            - name: MIN_CONF
              value: "0.15"
            - name: MODEL_DIR
              value: "/shared/model"

            # MIN_SUP mais baixo para gerar mais regras (0.2% = 2 playlists a cada 1000)
            - name: MIN_SUP
              value: "0.002"

            # Aumentar número máximo de regras por antecedente
            - name: MAX_RULES_PER_ANT
              value: "50"
          
          resources:
            requests:
              memory: "1Gi"
            limits:
              memory: "2G"

          volumeMounts:
            - name: shared
              mountPath: /shared
      volumes:
        - name: shared
          persistentVolumeClaim:
            claimName: project2-pvc