apiVersion: batch/v1
kind: Job
metadata:
  name: playlist-ml-ds2-001
  namespace: lucascosta
spec:
  backoffLimit: 1
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: ml-train
          image: docker.io/lukasalbukk/playlist-ml:0.1
          imagePullPolicy: Always
          env:
            - name: DATASET_URL
              value: "/home/lucascosta/devops/datasets/2023_spotify_ds2.csv"
            - name: PLAYLIST_COL
              value: "pid"
            - name: SONG_COL
              value: "track_name"
            - name: MIN_SUP
              value: "0.001"
            - name: MIN_CONF
              value: "0.2"
            - name: MODEL_DIR
              value: "/shared/model"
          volumeMounts:
            - name: shared
              mountPath: /shared
      volumes:
        - name: shared
          persistentVolumeClaim:
            claimName: project2-pvc
