# k8s/job-ml-ds2.yaml
apiVersion: batch/v1
kind: Job
metadata:
  # 1. Mudamos o nome para '004' (o '003' falhou)
  name: playlist-ml-ds2-004
  namespace: lucascosta
spec:
  backoffLimit: 1
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: ml-train
          image: docker.io/lukasalbukk/playlist-ml:0.1
          imagePullPolicy: Always
          env:
            - name: DATASET_URL
              value: "https://raw.githubusercontent.com/LukasAlbkk/devops/main/datasets/2023_spotify_ds2.csv"
            - name: PLAYLIST_COL
              value: "pid"
            - name: SONG_COL
              value: "track_name"
            - name: MIN_CONF
              value: "0.2"
            - name: MODEL_DIR
              value: "/shared/model"
            
            # CORREÇÃO: Usando MIN_SUP baixo (porque agora temos o MAX_BASKETS)
            - name: MIN_SUP
              value: "0.005" # 0.5% (muito mais regras)

            # CORREÇÃO: Adicionando o MAX_BASKETS
            - name: MAX_BASKETS
              value: "50000" # Amostra de 50k
          
          # Pedindo o máximo de memória (2G)
          resources:
            requests:
              memory: "1Gi"
            limits:
              memory: "2G"

          volumeMounts:
            - name: shared
              mountPath: /shared
      volumes:
        - name: shared
          persistentVolumeClaim:
            claimName: project2-pvc