# k8s/job-ml-ds2.yaml
apiVersion: batch/v1
kind: Job
metadata:
  # 1. Mudamos o nome DE NOVO (para '003')
  name: playlist-ml-ds2-003
  namespace: lucascosta
spec:
  backoffLimit: 1
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: ml-train
          image: docker.io/lukasalbukk/playlist-ml:0.1
          imagePullPolicy: Always
          env:
            - name: DATASET_URL
              value: "https://raw.githubusercontent.com/LukasAlbkk/devops/main/datasets/2023_spotify_ds2.csv"
            - name: PLAYLIST_COL
              value: "pid"
            - name: SONG_COL
              value: "track_name"
            - name: MIN_CONF
              value: "0.2"
            - name: MODEL_DIR
              value: "/shared/model"
            
            # 2. Correção para OOMKilled: Aumentando MAIS AINDA (5% -> 10%)
            - name: MIN_SUP
              value: "0.1"
          
          # 3. Correção para OOMKilled: Pedindo o MÁXIMO de memória permitido (2G)
          resources:
            requests:
              memory: "1Gi"
            limits:
              memory: "2G"

          volumeMounts:
            - name: shared
              mountPath: /shared
      volumes:
        - name: shared
          persistentVolumeClaim:
            claimName: project2-pvc