apiVersion: batch/v1
kind: Job
metadata:
  name: playlist-ml-ds1-002
  namespace: lucascosta
spec:
  backoffLimit: 1
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: ml-train
          image: docker.io/lukasalbukk/playlist-ml:0.1
          imagePullPolicy: Always
          env:
            - name: DATASET_URL
              value: "https://raw.githubusercontent.com/LukasAlbkk/devops/main/datasets/2023_spotify_ds1.csv"
            - name: PLAYLIST_COL
              value: "pid"
            - name: SONG_COL
              value: "track_name"
            - name: MIN_CONF
              value: "0.2"
            - name: MODEL_DIR
              value: "/shared/model"
            
            - name: MIN_SUP
              value: "0.005"
          
          resources:
            requests:
              memory: "1Gi"
            limits:
              memory: "2Gi"

          volumeMounts:
            - name: shared
              mountPath: /shared
      volumes:
        - name: shared
          persistentVolumeClaim:
            claimName: project2-pvc