apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: project2-pvc
  namespace: lucascosta
spec:
  storageClassName: default-storage-class-lucascosta
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      namespace: lucascosta
