apiVersion: v1
kind: Service
metadata:
  name: lucascosta-playlist-svc
  namespace: lucascosta
  labels:
    app: lucascosta-playlist-recommender
spec:
  type: ClusterIP
  selector:
    app: lucascosta-playlist-recommender
    tier: api
  ports:
    - name: http
      port: 50018        
      targetPort: 5000   
