apiVersion: v1
kind: Service
metadata:
  name: playlist-api-svc
  namespace: lucascosta
spec:
  type: ClusterIP
  selector:
    app: lucascosta-playlist-recommender
  ports:
    - name: http
      port: 30502
      targetPort: 5000
      protocol: TCP
